apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: webgraphs
type: Opaque
stringData:
  mysql-root-password: root
  mysql-database: webgraphs
  mysql-user: webgraphs_user
  mysql-password: secret
